---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 0979.
--- DateTime: 2022/8/4 15:34
---
function start()
    print("1----helloword")
    a = 4396
    print("2----" .. a)
end

function ttk()
    print("3----遇到敌人了")
end

function attack(str)
    print("4----choose action")
    print("5----" .. str)
    return "6----准备攻击"
end

